# Generated by Django 5.2.5 on 2025-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemcontato',
            options={'ordering': ['status', '-data_envio'], 'verbose_name': 'Mensagem de Contato', 'verbose_name_plural': 'Mensagens de Contato'},
        ),
        migrations.RemoveField(
            model_name='mensagemcontato',
            name='lida',
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='anotacoes_admin',
            field=models.TextField(blank=True, help_text='Este campo é visível apenas para administradores.', null=True, verbose_name='Anotações Internas'),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='status',
            field=models.CharField(choices=[('nao_lida', 'Não Lida'), ('em_tratamento', 'Em Tratamento'), ('lida', 'Lida')], default='nao_lida', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='assunto',
            field=models.CharField(choices=[('duvida', 'Dúvida'), ('sugestao', 'Sugestão'), ('reclamacao', 'Reclamação'), ('reserva', 'Reservar para evento'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
