# Generated by Django 5.2.4 on 2025-08-03 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Campo Society 1', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Detalhes sobre o espaço.', null=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto de destaque do espaço.', null=True, upload_to='espacos_fotos/')),
                ('tipo', models.CharField(choices=[('campo', 'Campo'), ('churrasqueira', 'Churrasqueira'), ('quiosque', 'Quiosque')], help_text='Tipo de espaço.', max_length=20)),
                ('capacidade', models.PositiveIntegerField(help_text='Número máximo de pessoas que o espaço comporta.')),
                ('disponivel', models.BooleanField(default=True, help_text='Marque se o espaço está disponível para novas reservas.')),
            ],
        ),
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, help_text='Ex: Manutenção, Evento fechado.', max_length=255, null=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='core.espaco')),
            ],
        ),
        migrations.CreateModel(
            name='RegraPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por hora neste horário específico.', max_digits=8)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_preco', to='core.espaco')),
            ],
        ),
    ]
