# Generated by Django 5.2.4 on 2025-08-03 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_espaco_bloqueio_regrapreco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Manhã, Tarde, Dia Inteiro', max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='espaco',
            name='modelo_de_cobranca',
            field=models.CharField(choices=[('hora', 'Por Hora'), ('periodo', 'Por Período')], default='hora', max_length=10),
        ),
        migrations.AddField(
            model_name='regrapreco',
            name='aplicar_em_feriados',
            field=models.BooleanField(default=False, help_text='Marque se este preço deve ser usado em feriados, sobrescrevendo o dia da semana normal.'),
        ),
        migrations.AlterField(
            model_name='bloqueio',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='capacidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='espacos_fotos/'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='tipo',
            field=models.CharField(choices=[('campo', 'Campo'), ('churrasqueira', 'Churrasqueira'), ('quiosque', 'Quiosque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regrapreco',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo'), (7, 'Dias de Semana (Seg-Sex)'), (8, 'Final de Semana (Sáb-Dom)'), (9, 'Segunda a Quinta (Seg-Qui)'), (10, 'Segundas, Quartas e Sextas (Seg-Qua-Sex)'), (11, 'Terças e Quintas (Ter-Qui)')]),
        ),
        migrations.AlterField(
            model_name='regrapreco',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_preco_hora', to='core.espaco'),
        ),
        migrations.AlterField(
            model_name='regrapreco',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='PrecoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo'), (7, 'Dias de Semana (Seg-Sex)'), (8, 'Final de Semana (Sáb-Dom)'), (9, 'Segunda a Quinta (Seg-Qui)'), (10, 'Segundas, Quartas e Sextas (Seg-Qua-Sex)'), (11, 'Terças e Quintas (Ter-Qui)')])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aplicar_em_feriados', models.BooleanField(default=False, help_text='Marque se este preço deve ser usado em feriados.')),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_preco_periodo', to='core.espaco')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodo')),
            ],
        ),
    ]
