# Generated by Django 5.2.4 on 2025-08-03 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feriado_periodo_espaco_modelo_de_cobranca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueio',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_data', to='core.espaco'),
        ),
        migrations.CreateModel(
            name='BloqueioRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo'), (7, 'Dias de Semana (Seg-Sex)'), (8, 'Final de Semana (Sáb-Dom)'), (9, 'Segunda a Quinta (Seg-Qui)'), (10, 'Segundas, Quartas e Sextas (Seg-Qua-Sex)'), (11, 'Terças e Quintas (Ter-Qui)')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(blank=True, help_text='Ex: Manutenção semanal, Aula fixa', max_length=255, null=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recorrentes', to='core.espaco')),
            ],
        ),
    ]
