# Generated by Django 5.2.4 on 2025-08-05 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
