# Generated by Django 4.2.7 on 2025-08-08 00:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloqueioRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo'), (7, 'Dias de Semana (Seg-Sex)'), (8, 'Final de Semana (Sáb-Dom)'), (9, 'Segunda a Quinta (Seg-Qui)'), (10, 'Segundas, Quartas e Sextas (Seg-Qua-Sex)'), (11, 'Terças e Quintas (Ter-Qui)')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('motivo', models.CharField(blank=True, help_text='Ex: Manutenção semanal, Aula fixa', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='espacos_fotos/')),
                ('tipo', models.CharField(choices=[('campo', 'Campo'), ('churrasqueira', 'Churrasqueira'), ('quiosque', 'Quiosque')], max_length=20)),
                ('capacidade', models.PositiveIntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('modelo_de_cobranca', models.CharField(choices=[('hora', 'Por Hora'), ('periodo', 'Por Período')], default='hora', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Manhã, Tarde, Dia Inteiro', max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo'), (7, 'Dias de Semana (Seg-Sex)'), (8, 'Final de Semana (Sáb-Dom)'), (9, 'Segunda a Quinta (Seg-Qui)'), (10, 'Segundas, Quartas e Sextas (Seg-Qua-Sex)'), (11, 'Terças e Quintas (Ter-Qui)')])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aplicar_em_feriados', models.BooleanField(default=False, help_text='Marque se este preço deve ser usado em feriados.')),
            ],
        ),
        migrations.CreateModel(
            name='RegraPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo'), (7, 'Dias de Semana (Seg-Sex)'), (8, 'Final de Semana (Sáb-Dom)'), (9, 'Segunda a Quinta (Seg-Qui)'), (10, 'Segundas, Quartas e Sextas (Seg-Qua-Sex)'), (11, 'Terças e Quintas (Ter-Qui)')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aplicar_em_feriados', models.BooleanField(default=False, help_text='Marque se este preço deve ser usado em feriados.')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendente', 'Pendente de Pagamento'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.espaco')),
            ],
        ),
    ]
