# Generated by Django 4.2.7 on 2025-08-08 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regrapreco',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_preco_hora', to='reservas.espaco'),
        ),
        migrations.AddField(
            model_name='precoperiodo',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_preco_periodo', to='reservas.espaco'),
        ),
        migrations.AddField(
            model_name='precoperiodo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.periodo'),
        ),
        migrations.AddField(
            model_name='bloqueiorecorrente',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_recorrentes', to='reservas.espaco'),
        ),
        migrations.AddField(
            model_name='bloqueio',
            name='espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_data', to='reservas.espaco'),
        ),
    ]
