# Generated by Django 5.2.5 on 2025-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observacoes_admin',
            field=models.TextField(blank=True, help_text='Anotações internas visíveis apenas para a administração.', null=True, verbose_name='Observações do Administrador'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('nao_lida', 'Não Lida'), ('em_tratamento', 'Em Tratamento'), ('tratado', 'Tratado')], default='nao_lida', max_length=20),
        ),
    ]
