# Generated by Django 5.2.5 on 2025-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_observacoes_admin_alter_reserva_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('nao_lida', 'Não Lida'), ('em_tratamento', 'Em Tratamento'), ('tratado', 'Tratado'), ('cancelada_pelo_usuario', 'Cancelada pelo Usuário')], default='nao_lida', max_length=30),
        ),
    ]
